export const recetas = [
        {
            id:0,
            Nombre: "Pozole",
            Autor: "El esponja1",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:1,
            Nombre: "Pozole",
            Autor: "El esponja2",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:6,
            Nombre: "Pozole",
            Autor: "El esponja3",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 6,
            Dislikes:0,
        },
        {
            id:3,
            Nombre: "Pozole",
            Autor: "El esponja4",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:6,
            Nombre: "Pozole",
            Autor: "El esponja5",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 8,
            Dislikes:0,
        },
        {
            id:5,
            Nombre: "Pozole",
            Autor: "El esponja6",
            imagen: "../assets/pozole.jpg",
            Descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus justo purus, porta sit amet lectus non, auctor dictum nisi. Maecenas sit amet imperdiet lacus. Nam maximus libero id elit condimentum porttitor. Praesent pretium scelerisque quam sodales ultrices.",
            Likes: 2,
            Dislikes:0,
        }
]
