export const recetas = [
        {
            id:0,
            Nombre: "Birria",
            Autor: "Lizbeth",
            imagen: "./assets/birria.jpg",
            Descripcion: "La birria es, en la gastronomía mexicana, un plato a base de carne de borrego o carnero estrictamente (aunque en algunas regiones se prepara con carne de chivo y en algunas partes del norte, con carne de res), adobado con una preparación a base de algunos tipos de chiles, condimentos y sal.",
            Preparacion: "Pon a asar en un comal los jitomates, los chiles y los ajos, cuidando que estos últimos no se tuesten porque se amargan. Retira las semillas y pon a hervir los chiles en agua. Muele los chiles con los ajos, las pimientas, el orégano, sal y el pulque. Si no agregas pulque, usa el agua en la que herviste los chiles para poder molerlos. Unta la carne con sal de grano y báñala con la salsa. Refrigera durante un día. Cocina en una olla a presión por una hora o hasta que la carne se desprenda del hueso. Retira la carne del fuego y cuélala. Quita la piel de los jitomates y lícualos con el caldo de carne. Cocina a fuego medio por 15 minutos. Agrega la carne. Sirve con cilantro, cebolla y chile de árbol. Exprime limón al gusto.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:1,
            Nombre: "Boneless BBQ",
            Autor: "Lizbeth",
            imagen: "./assets/Boneless.jpg",
            Descripcion: "Los boneless es más como una botana preparada de piezas de pollo sin hueso cortados en piezas pequeñas, empanizados y cubiertos con alguna salsa de la preferencia de cada persona y si se requiere se acompaña con un aderezo.",
            Preparacion: "Salpimienta los cubos de pechuga. En un recipiente mezcla la harina con el agua. Pasa los cubos por la mezcla y fríelos en una sartén con aceite. Para la salsa, licúa el resto de los ingredientes. Baña los boneless con la salsa y sirve.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:6,
            Nombre: "Carne en Adobo",
            Autor: "Lizbeth",
            imagen: "./assets/adobo.jpg",
            Descripcion: "El adobo es un preparado gastronómico en forma de caldo o salsa de distintos componentes (pimentón, orégano, sal, ajos y vinagre) mezclados según el lugar de procedencia y alimento en el que se vaya a usar destinado principalmente a conservar y realizar el alimento.",
            Preparacion: "En la olla de presión cocina la carne junto con la cebolla, el ajo, el laurel, sal y agua suficiente para cubrirlos durante 30 minutos después de que escape el vapor o hasta que la carne esté cocida. Espera a que se enfríe la olla antes de abrirla, saca la carne y reserva 3 tazas de caldo. Licúa los chiles con 1 taza de agua, el ajo y la cebolla, cuela sobre una cacerola con aceite, a fuego bajo, hasta que hierva. Licúa el resto de los ingredientes y cuela sobre la salsa. Integra las calabazas, sazona y cuando hierva, incorpora la carne para que se caliente y sirve.",
            Likes: 6,
            Dislikes:0,
        },
        {
            id:3,
            Nombre: "Chiles en nogada",
            Autor: "Lizbeth",
            imagen: "./assets/chiles_en_nogada.jpg",
            Descripcion: "El chile en nogada es uno de los platillos típicos de la gastronomía del estado de Puebla. Se prepara con chile poblano relleno de un guisado de picadillo y frutas, que incluye acitrón y que se cubre con salsa de nuez (nogada), perejil y granada.",
            Preparacion: "Barniza los chiles con un poco de aceite y asalos en un comal o en el horno, voltéalos hasta que se tueste la piel. Mételos en una bolsa de plástico sellada por 30 minutos, quita la cáscara y desvénalos. Corta el durazno y la pera en cubitos y tuesta un poco las almendras. Pica el ajo, la cebolla y los jitomates, y fríelos en aceite. Agrega la carne y salpimenta, luego deja a fuego medio durante 15 minutos. Fríe el plátano macho, picado, y agrega a la carne junto con las frutas. Por último, incluye las almendras, los piñones y pasas. Cocina a fuego bajo por cinco minutos y retira de la flama. Para la nogada, pela las nueces y licúalas con las almendras, el queso, la crema, leche condensada y el jerez. Rellena los chiles con la carne. Para servir, vierte un poco de crema en el plato y cubre con granada y perejil picado.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:9,
            Nombre: "Alitas de mango y abanero",
            Autor: "Lizbeth",
            imagen: "./assets/alitas.jpg",
            Descripcion: "Las alitas son secciones de pollo que corresponden a las alas que se fríen y se recubren en salsas especiales. La tradicional ala de pollo elaborada al estilo Buffalo se compone de dos ingredientes: una salsa picante (a base de vinagre y cayena) y margarina o mantequilla.",
            Preparacion: "Mezcla la harina, sal, pimienta y el ajo en polvo. Cubre las alitas con la mezcla y fríelas. Licua la pulpa de mango con salsa de habanero y cubre las alitas con la salsa.",
            Likes: 8,
            Dislikes:0,
        },
        {
            id:4,
            Nombre: "Enchiladas verdes",
            Autor: "Lizbeth",
            imagen: "./assets/enchiladas_verdes.png",
            Descripcion: "La enchilada es un plato que en México se elabora con tortilla de maíz bañada en alguna salsa picante utilizando chile en su preparación. Dependiendo del estilo, la enchilada puede ir acompañada o rellena de carnes como pollo, pavo, res o queso, además de ser acompañada de alguna guarnición adicional, que generalmente consiste en cebolla fresca picada o en rodajas, lechuga, crema de leche y queso.",
            Preparacion: "Hierve los tomates, chile serrano, ajo y cebolla en el caldo de pollo durante 10 minutos y licua con el cilantro. Salpimenta y conserva caliente. Fríe ligeramente las tortillas en el aceite caliente y escurre. Sumerge las tortillas en la salsa, rellena con el pollo y baña con más salsa. Decora con el queso, crema, cebolla cambray y cilantro picado.",
            Likes: 2,
            Dislikes:0,
        },
        {
            id:2,
            Nombre: "Pancita",
            Autor: "Lizbeth",
            imagen: "./assets/pancita.jpg",
            Descripcion: "Este platillo en algunos lugares se piensa que es como remedio para curar las resacas, aunque en México también se consume tradicionalmente como plato que se sirve en ocasiones especiales o con la familia, sobre todo en las mañanas como desayuno. Suele acompañarse con una salsa roja picante y tortillas recién hechas, además de un refresco o cerveza muy fría.",
            Preparacion: "Hierve los chiles con los jitomates; lícualos junto con el ajo. Regresa a la olla y mantén el hervor. Mientras tanto enjuaga la pancita en agua corriendo hasta que el agua salga limpia. Agrega la carne al caldo junto con el epazote y cuece por 40 minutos. Pica la pancita. Distribuye las porciones; agrega el caldo. Esparce un poco de cebolla, orégano y chile de árbol. Sirve",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:7,
            Nombre: "Espagueti",
            Autor: "Lizbeth",
            imagen: "./assets/espagueti.jpg",
            Descripcion: "El espagueti es un tipo de pasta italiana elaborada con harina de grano duro y agua. Tiene forma delgada, cuerda larga y sección circular. Se trata de uno de los ingredientes más representativos de la gastronomía italiana cuya popularidad trasciende a otros países.",
            Preparacion: "Hierve 2 litros de agua y, cuando esté en su punto, agrega 2 cucharadas de sal. Posteriormente, cuece la pasta hasta que esté blanda. Retira del fuego, cuela la pasta y desecha el agua. Hierve el puré de jitomate a fuego lento y añade la crema, la mantequilla y el cubo sazonador. Vierte el espagueti en la salsa y mezcla. Sirve. Espolvorea con el queso parmesano al gusto",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:8,
            Nombre: "Hamburguesa",
            Autor: "Lizbeth",
            imagen: "./assets/hamburguesa.png",
            Descripcion: "Una hamburguesa es un tipo de sándwich hecho a base de carne molida aglutinada en forma de filete cocinado a la parrilla o a la plancha, aunque también puede freírse u hornearse. Suele estar acompañada de aros de cebolla, hojas de lechuga, alguna rodaja de tomate, láminas de encurtidos y patatas fritas.",
            Preparacion: "Salpimenta el pollo. Mezcla la harina con el huevo y leche, agrega una cucharadita de sal, pasa las piezas de pollo por la mezcla y después por el pan molido; vuelve a pasar por la mezcla y una vez más en el pan molido. Coloca en la parrilla hasta que se doren las piezas de pollo. Mientras tanto, combina la col con la zanahoria y cebolla morada, salpimenta. Tuesta el pan, unta un poco de mayonesa y termina con el pollo y ensalada de col.",
            Likes: 4,
            Dislikes:0,
        },
        {
            id:5,
            Nombre: "Pozole",
            Autor: "Lizbeth",
            imagen: "./assets/pozole.jpg",
            Descripcion: "El pozole es un plato tradicional mexicano, un caldo hecho a base de granos de maíz al que se agrega, según la región, carne de pollo o de cerdo como ingrediente secundarioSe acompaña con algunas verduras como el rabano, lechuga, cebolla y condimentos como chile en polvo y oregano.",
            Preparacion: "Lava el maíz y ponlo a hervir en olla de presión durante 20 minutos. Aparte, pon a cocer el pollo en una cacerola con un poco de sal. Deshebra y reserva el caldo. Asa los chiles, retira las semillas y remójalos en agua caliente por 10 minutos. Licúa los chiles con la cebolla y el ajo en la misma agua donde pusiste los chiles. Fríe la mezcla en un poco de aceite y añádelo al caldo de pollo. Cuela el maíz y agrégalo al caldo también. Deja hervir otros 10 minutos más. Dispón en la mesa la crema, lechuga, rábanos, limones, orégano, aguacate, chile y tostadas para montar sobre cada plato.",
            Likes: 2,
            Dislikes:0,
        }
]
