export const recetas = [
        {
            id:0,
            Nombre: "Birria",
            Autor: "Lizbeth",
            imagen: "../assets/birria.jpg",
            Descripcion: "La birria es, en la gastronomía mexicana, un plato a base de carne de borrego o carnero estrictamente (aunque en algunas regiones se prepara con carne de chivo y en algunas partes del norte, con carne de res), adobado con una preparación a base de algunos tipos de chiles, condimentos y sal.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:1,
            Nombre: "Boneless",
            Autor: "Lizbeth",
            imagen: "../assets/Boneless.jpg",
            Descripcion: "Los boneless es más como una botana preparada de piezas de pollo sin hueso cortados en piezas pequeñas, empanizados y cubiertos con alguna salsa de la preferencia de cada persona y si se requiere se acompaña con un aderezo.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:6,
            Nombre: "Adobo",
            Autor: "Lizbeth",
            imagen: "../assets/adobo.jpg",
            Descripcion: "El adobo es un preparado gastronómico en forma de caldo o salsa de distintos componentes (pimentón, orégano, sal, ajos y vinagre) mezclados según el lugar de procedencia y alimento en el que se vaya a usar destinado principalmente a conservar y realizar el alimento.",
            Likes: 6,
            Dislikes:0,
        },
        {
            id:3,
            Nombre: "Chiles en nogada",
            Autor: "Lizbeth",
            imagen: "../assets/chiles_en_nogada.jpg",
            Descripcion: "El chile en nogada es uno de los platillos típicos de la gastronomía del estado de Puebla. Se prepara con chile poblano relleno de un guisado de picadillo y frutas, que incluye acitrón y que se cubre con salsa de nuez (nogada), perejil y granada.",
            Likes: 5,
            Dislikes:0,
        },
        {
            id:9,
            Nombre: "Alitas de mango y abanero",
            Autor: "Lizbeth",
            imagen: "../assets/alitas.jpg",
            Descripcion: "Las alitas son secciones de pollo que corresponden a las alas que se fríen y se recubren en salsas especiales. La tradicional ala de pollo elaborada al estilo Buffalo se compone de dos ingredientes: una salsa picante (a base de vinagre y cayena) y margarina o mantequilla.",
            Likes: 8,
            Dislikes:0,
        },
        {
            id:4,
            Nombre: "Enchiladas verdes",
            Autor: "Lizbeth",
            imagen: "../assets/enchiladas_verdes.png",
            Descripcion: "La enchilada es un plato que en México se elabora con tortilla de maíz bañada en alguna salsa picante utilizando chile en su preparación. Dependiendo del estilo, la enchilada puede ir acompañada o rellena de carnes como pollo, pavo, res o queso, además de ser acompañada de alguna guarnición adicional, que generalmente consiste en cebolla fresca picada o en rodajas, lechuga, crema de leche y queso.",
            Likes: 2,
            Dislikes:0,
        },
        {
            id:2,
            Nombre: "Pancita",
            Autor: "Lizbeth",
            imagen: "../assets/pancita.jpg",
            Descripcion: "Este platillo en algunos lugares se piensa que es como remedio para curar las resacas, aunque en México también se consume tradicionalmente como plato que se sirve en ocasiones especiales o con la familia, sobre todo en las mañanas como desayuno. Suele acompañarse con una salsa roja picante y tortillas recién hechas, además de un refresco o cerveza muy fría.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:7,
            Nombre: "Espagueti",
            Autor: "Lizbeth",
            imagen: "../assets/espagueti.jpg",
            Descripcion: "El espagueti es un tipo de pasta italiana elaborada con harina de grano duro y agua. Tiene forma delgada, cuerda larga y sección circular. Se trata de uno de los ingredientes más representativos de la gastronomía italiana cuya popularidad trasciende a otros países.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:8,
            Nombre: "Hamburguesa",
            Autor: "Lizbeth",
            imagen: "../assets/hamburguesa.png",
            Descripcion: "Una hamburguesa es un tipo de sándwich hecho a base de carne molida aglutinada en forma de filete cocinado a la parrilla o a la plancha, aunque también puede freírse u hornearse. Suele estar acompañada de aros de cebolla, hojas de lechuga, alguna rodaja de tomate, láminas de encurtidos y patatas fritas.",
            Likes: 3,
            Dislikes:0,
        },
        {
            id:5,
            Nombre: "Pozole",
            Autor: "Lizbeth",
            imagen: "../assets/pozole.jpg",
            Descripcion: "El pozole es un plato tradicional mexicano, un caldo hecho a base de granos de maíz al que se agrega, según la región, carne de pollo o de cerdo como ingrediente secundarioSe acompaña con algunas verduras como el rabano, lechuga, cebolla y condimentos como chile en polvo y oregano.",
            Likes: 2,
            Dislikes:0,
        }
]
